on:
  workflow_dispatch:

name: Build static aria2 binary

jobs:
  build:
    name: Build aria2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        env:
          PLATFORMS: "linux/amd64,linux/arm64"
        uses: docker/bake-action@v2

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aria2
          path: build/**

